[package]
name = "r64drive"
version = "0.1.0"
authors = ["Andrew Wygle <awygle@gmail.com>"]
edition = "2018"

[dependencies]
safe-ftdi = "*"
byteorder = "*"
num = "*"
num-derive = "*"
num-traits = "*"
